DROP DATABASE IF EXISTS TG4;
CREATE DATABASE TG4;

USE TG4;

CREATE TABLE jugadores (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(25) NOT NULL,
	pass VARCHAR(25) NOT NULL,
	bingos INTEGER,
	lineas INTEGER)ENGINE=InnoDB;

CREATE TABLE partidas (
	id INT PRIMARY KEY,
	jugadores VARCHAR(512) NOT NULL,
	bote INTEGER,
	diahora DATETIME)ENGINE=InnoDB;

CREATE TABLE relacion (
	id_j INTEGER,
	id_p INTEGER,
	puntos INTEGER,
	FOREIGN KEY (id_j) REFERENCES jugadores(id) ON DELETE CASCADE,
	FOREIGN KEY (id_p) REFERENCES partidas(id))ENGINE=InnoDB;